name: 'Deploy to Digital Ocean'
description: 'Greet someone and record the time'
on: 
  push:
    branches:
     - main

jobs:
  deploy:
    name: Deploy to Digital Ocean
    runs-on: ubuntu-latest # select the vm to work on
    steps:
      - name: Deploy node app
        uses: applboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
        script: |
          mkdir test
          cd test
          git clone git@github.com:too-old-to-code/nginx-play.git
          echo 'Deployment successful to Digital Ocean'
      
