version: "3.9"
services:
  andy:
    depends_on:
      - reverse-proxy
    build: ./html/andy
  ricky:
    depends_on:
      - reverse-proxy
    build: ./html/ricky
  default:
    depends_on:
      - reverse-proxy
    build: ./html/default
  reverse-proxy:
    restart: always
    image: nginx:latest
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    ports:
    - "80:80"